package Vistas;

/**
 *
 * @author grazia
 * @author elohym
 * @author andres
 */
public class MainVentana extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainVentana.class.getName());

    /**
     * Creates new form MainVentana
     */
    public MainVentana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelIzquierdo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        btnNuevo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnCSV = new javax.swing.JButton();
        panelIzquierdo1 = new javax.swing.JPanel();
        estado = new javax.swing.JLabel();
        tiempo = new javax.swing.JLabel();
        btnEliminarCola = new javax.swing.JButton();
        btnLiberarImpresora = new javax.swing.JButton();
        encola = new javax.swing.JLabel();
        PanelDocumentos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        btnEliminarDocumento = new javax.swing.JButton();
        btnEnviarImpresion = new javax.swing.JButton();
        btnNuevoDocumento1 = new javax.swing.JButton();
        PanelColaLista = new javax.swing.JPanel();
        btnVerLista = new javax.swing.JButton();
        btnVerLista1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Cola de Impresión");
        setBackground(new java.awt.Color(246, 241, 248));

        panelSuperior.setBackground(new java.awt.Color(233, 221, 245));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(74, 74, 74));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de Cola de Impresión");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSuperior.add(jLabel1);

        panelIzquierdo.setBackground(new java.awt.Color(243, 234, 247));
        panelIzquierdo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuarios Del Sistema", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(90, 78, 109))); // NOI18N
        panelIzquierdo.setForeground(new java.awt.Color(217, 203, 234));
        panelIzquierdo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        panelIzquierdo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 37, 340, 249));

        btnNuevo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(175, 189, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);
        panelIzquierdo.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 98, 32));

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 153, 255));
        jButton1.setText("Eliminar");
        jButton1.setMaximumSize(new java.awt.Dimension(75, 24));
        jButton1.setMinimumSize(new java.awt.Dimension(75, 24));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        panelIzquierdo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 98, 32));

        btnCSV.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCSV.setForeground(new java.awt.Color(255, 153, 204));
        btnCSV.setText("CSV");
        btnCSV.setMaximumSize(new java.awt.Dimension(75, 24));
        btnCSV.setMinimumSize(new java.awt.Dimension(75, 24));
        btnCSV.addActionListener(this::btnCSVActionPerformed);
        panelIzquierdo.add(btnCSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 98, 32));

        panelIzquierdo1.setBackground(new java.awt.Color(255, 241, 255));
        panelIzquierdo1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control de Impresion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(107, 78, 109))); // NOI18N
        panelIzquierdo1.setForeground(new java.awt.Color(217, 203, 234));
        panelIzquierdo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        estado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        estado.setForeground(new java.awt.Color(102, 102, 102));
        estado.setText("Estado: Listo");
        panelIzquierdo1.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        tiempo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tiempo.setForeground(new java.awt.Color(102, 102, 102));
        tiempo.setText("Tiempo: 00:00:00 ");
        panelIzquierdo1.add(tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        btnEliminarCola.setBackground(new java.awt.Color(255, 153, 204));
        btnEliminarCola.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnEliminarCola.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCola.setText("Eliminar de Cola");
        btnEliminarCola.addActionListener(this::btnEliminarColaActionPerformed);
        panelIzquierdo1.add(btnEliminarCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 310, 50));

        btnLiberarImpresora.setBackground(new java.awt.Color(183, 156, 237));
        btnLiberarImpresora.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnLiberarImpresora.setForeground(new java.awt.Color(255, 255, 255));
        btnLiberarImpresora.setText("Liberar Impresora");
        btnLiberarImpresora.addActionListener(this::btnLiberarImpresoraActionPerformed);
        panelIzquierdo1.add(btnLiberarImpresora, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 310, 50));

        encola.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        encola.setForeground(new java.awt.Color(102, 102, 102));
        encola.setText(" En cola: 0 documentos  ");
        panelIzquierdo1.add(encola, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        PanelDocumentos.setBackground(new java.awt.Color(243, 234, 247));
        PanelDocumentos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Documentos del Usuario Seleccionado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(90, 78, 109))); // NOI18N
        PanelDocumentos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelDocumentos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 730, 190));

        btnEliminarDocumento.setBackground(new java.awt.Color(255, 153, 204));
        btnEliminarDocumento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEliminarDocumento.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarDocumento.setText("Eliminar Documento");
        btnEliminarDocumento.addActionListener(this::btnEliminarDocumentoActionPerformed);
        PanelDocumentos.add(btnEliminarDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 170, 40));

        btnEnviarImpresion.setBackground(new java.awt.Color(0, 221, 221));
        btnEnviarImpresion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEnviarImpresion.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarImpresion.setText("Enviar Impresión");
        btnEnviarImpresion.addActionListener(this::btnEnviarImpresionActionPerformed);
        PanelDocumentos.add(btnEnviarImpresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 160, 40));

        btnNuevoDocumento1.setBackground(new java.awt.Color(175, 189, 255));
        btnNuevoDocumento1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNuevoDocumento1.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoDocumento1.setText("Nuevo Documento");
        btnNuevoDocumento1.addActionListener(this::btnNuevoDocumento1ActionPerformed);
        PanelDocumentos.add(btnNuevoDocumento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 160, 40));

        PanelColaLista.setBackground(new java.awt.Color(255, 241, 255));
        PanelColaLista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vista de la Cola de Impresión", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(107, 78, 109))); // NOI18N
        PanelColaLista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVerLista.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVerLista.setForeground(new java.awt.Color(255, 153, 204));
        btnVerLista.setText("Ver como Árbol");
        btnVerLista.addActionListener(this::btnVerListaActionPerformed);
        PanelColaLista.add(btnVerLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 160, 30));

        btnVerLista1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVerLista1.setForeground(new java.awt.Color(175, 189, 255));
        btnVerLista1.setText("Ver como Lista");
        btnVerLista1.addActionListener(this::btnVerLista1ActionPerformed);
        PanelColaLista.add(btnVerLista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 160, 30));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        PanelColaLista.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 710, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelColaLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelDocumentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelIzquierdo1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelIzquierdo1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelIzquierdo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelColaLista, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCSVActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnLiberarImpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarImpresoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLiberarImpresoraActionPerformed

    private void btnEliminarColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarColaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarColaActionPerformed

    private void btnNuevoDocumento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoDocumento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoDocumento1ActionPerformed

    private void btnEnviarImpresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarImpresionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarImpresionActionPerformed

    private void btnEliminarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarDocumentoActionPerformed

    private void btnVerLista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerLista1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerLista1ActionPerformed

    private void btnVerListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainVentana().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelColaLista;
    private javax.swing.JPanel PanelDocumentos;
    private javax.swing.JButton btnCSV;
    private javax.swing.JButton btnEliminarCola;
    private javax.swing.JButton btnEliminarDocumento;
    private javax.swing.JButton btnEnviarImpresion;
    private javax.swing.JButton btnLiberarImpresora;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnNuevoDocumento1;
    private javax.swing.JButton btnVerLista;
    private javax.swing.JButton btnVerLista1;
    private javax.swing.JLabel encola;
    private javax.swing.JLabel estado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelIzquierdo;
    private javax.swing.JPanel panelIzquierdo1;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JLabel tiempo;
    // End of variables declaration//GEN-END:variables
}
